### ISSUE TITLE
Query about the details

### ISSUE THREAD

**Issue by jwjoel** [MeteHanC/Python-Median-Filter#1]
Hi MeteHanC,

Thank you for your great code. It works perfectly.
I'm currently learning something about median filter, I'm curious about a line in your code:

if i + z - indexer < 0 or i + z - indexer > len(data) - 1:

I'm really struggling with the meaning of this. I wish if you could give me some tips. :)

Many thanks!

**Comment by MeteHanC** [comment]
Hey,

That line is about zero padding (It is an approach which you extend border values outside of the filter with zeros). So I use  'i + z - indexer < 0'  and 'i + z - indexer > len(data) - 1' to detect if filter is at the border. If so, I append zeros. If you have anything to ask please feel free to.
